### ISSUE TITLE
import aurige

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilib#15]
la prise en compte du fichier permet de supprimer en base les candidats non valides, un envoi de mail est bien déclenché mais le mail n'est pas reçu (alors que le mail de confirmation d'inscription fonctionne et utilise la même fonction).
les candidats valides reçoivent leur MagicLink mais leur statut isValid reste à false.

**Comment by philippeBron** [comment]
Erreur lors de l'import du fichier json
```
web_1  | ReferenceError: regeneratorRuntime is not defined
web_1  |     at /usr/src/app/dist/server.bundle.js:3359:49
web_1  |     at uploadAurigeJSON (/usr/src/app/dist/server.bundle.js:3396:4)
web_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
web_1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
web_1  |     at Immediate._onImmediate (/usr/src/app/node_modules/multer/lib/make-middleware.js:53:37)
web_1  |     at runCallback (timers.js:814:20)
web_1  |     at tryOnImmediate (timers.js:768:5)
web_1  |     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by philippeBron** [comment]
Ok sur environnement dev
